### ISSUE TITLE
Should Ensure<T>, with a provided validation function, check the value for null?

### ISSUE THREAD

**Issue by joaofbantunes** [afnpires/Ensure#1]
Was thinking of a way to improve `void Ensure<T>(this T value, Func<T, bool> validator, string message)`, to avoid boxing of the `value` when checking it for `null` but then realized, should it be check at all?

For all we know  the validation function could be something like `v => v == null || v.SomeOtherThing == "Awesome Value"`, or is this something you're assuming not supported?

**Comment by afnpires** [comment]
Yes, you're right. It should be the validators responsibility to validate the value. Will remove the `value`  `null` validation.
